# Generated by Django 5.2.16 on 2026-07-21 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ear_tag', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(choices=[('sheep', 'Sheep'), ('goat', 'Goat')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('missing', 'Missing')], default='active', max_length=20)),
                ('needs_attention', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.farm')),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.flock')),
            ],
            options={
                'ordering': ['ear_tag'],
            },
        ),
        migrations.AddConstraint(
            model_name='flock',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_flock_name_per_farm'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'status'], name='animals_ani_farm_id_f9fe7f_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'species'], name='animals_ani_farm_id_311f6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('farm', 'ear_tag'), name='unique_ear_tag_per_farm'),
        ),
    ]
