# Generated by Django 5.2.16 on 2026-07-21 22:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('general', 'General health'), ('injury', 'Injury'), ('illness', 'Illness'), ('parasite', 'Parasite concern'), ('reproductive', 'Reproductive'), ('other', 'Other')], default='general', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('summary', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_observations', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_observations', to='farms.farm')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_health_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topical', 'Topical'), ('other', 'Other')], default='other', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('withdrawal_end_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_treatments', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='farms.farm')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='health.healthobservation')),
            ],
            options={
                'ordering': ['-administered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='healthobservation',
            index=models.Index(fields=['farm', 'is_resolved', 'severity'], name='health_heal_farm_id_d56cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['farm', 'administered_at'], name='health_trea_farm_id_01dbd6_idx'),
        ),
    ]
