# Generated by Django 5.2.16 on 2026-07-22 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_animallifecycleevent'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_on', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('body_condition_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurements', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurements', to='farms.farm')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_weight_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_on', '-created_at'],
                'indexes': [models.Index(fields=['farm', 'measured_on'], name='growth_weig_farm_id_2d06c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('animal', 'measured_on'), name='unique_animal_weight_per_day')],
            },
        ),
    ]
