# Generated by Django 5.2.16 on 2026-07-22 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_animallifecycleevent'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('concentration', models.CharField(blank=True, max_length=100)),
                ('stock_unit', models.CharField(default='ml', max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meat_withdrawal_days', models.PositiveSmallIntegerField(default=0)),
                ('milk_withdrawal_days', models.PositiveSmallIntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_products', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_batches', to='farms.farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='medicine.medicineproduct')),
            ],
            options={
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('started_on', models.DateField()),
                ('planned_doses', models.PositiveSmallIntegerField(default=1)),
                ('frequency_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('meat_withdrawal_end_date', models.DateField(blank=True, null=True)),
                ('milk_withdrawal_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_courses', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_courses', to='farms.farm')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_treatment_courses', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_courses', to='medicine.medicineproduct')),
            ],
            options={
                'ordering': ['-started_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoseAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_at', models.DateTimeField()),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_medicine_doses', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_administrations', to='farms.farm')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='medicine.medicinebatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='medicine.treatmentcourse')),
            ],
            options={
                'ordering': ['-administered_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicineproduct',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_farm_medicine'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['farm', 'expiry_date'], name='medicine_me_farm_id_3836a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_medicine_product_batch'),
        ),
        migrations.AddIndex(
            model_name='treatmentcourse',
            index=models.Index(fields=['farm', 'status', 'started_on'], name='medicine_tr_farm_id_d9d04e_idx'),
        ),
        migrations.AddIndex(
            model_name='doseadministration',
            index=models.Index(fields=['farm', 'administered_at'], name='medicine_do_farm_id_6f7f2e_idx'),
        ),
    ]
