# Generated by Django 5.2.16 on 2026-07-22 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farminvitation_farmmembershipaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=250)),
                ('animal_id', models.UUIDField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'created_at'], name='audit_audit_farm_id_046c14_idx'), models.Index(fields=['farm', 'resource_type', 'created_at'], name='audit_audit_farm_id_0076cf_idx'), models.Index(fields=['farm', 'animal_id', 'created_at'], name='audit_audit_farm_id_c78723_idx')],
            },
        ),
    ]
