# Generated by Django 5.2.16 on 2026-07-22 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('worker', 'Worker'), ('viewer', 'Viewer')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_farm_invitations', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='farms.farm')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_farm_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'status', 'email'], name='farms_farmi_farm_id_a5957a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FarmMembershipAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Invitation accepted'), ('role_changed', 'Role changed'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('invitation_revoked', 'Invitation revoked')], max_length=30)),
                ('subject_email', models.EmailField(max_length=254)),
                ('from_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Manager'), ('worker', 'Worker'), ('viewer', 'Viewer')], max_length=20)),
                ('to_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Manager'), ('worker', 'Worker'), ('viewer', 'Viewer')], max_length=20)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farm_membership_actions', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_audits', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'event_type', 'created_at'], name='farms_farmm_farm_id_36e638_idx')],
            },
        ),
    ]
