# Generated by Django 5.2.16 on 2026-07-22 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_animallifecycleevent'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeding_date', models.DateField()),
                ('expected_birth_date', models.DateField()),
                ('method', models.CharField(choices=[('natural', 'Natural service'), ('artificial', 'Artificial insemination'), ('unknown', 'Unknown')], default='natural', max_length=20)),
                ('status', models.CharField(choices=[('exposed', 'Exposed'), ('confirmed', 'Pregnancy confirmed'), ('not_pregnant', 'Not pregnant'), ('completed', 'Birth recorded')], default='exposed', max_length=20)),
                ('pregnancy_checked_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_as_dam', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='farms.farm')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_breeding_records', to=settings.AUTH_USER_MODEL)),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='breeding_as_sire', to='animals.animal')),
            ],
            options={
                'ordering': ['expected_birth_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField()),
                ('total_born', models.PositiveSmallIntegerField()),
                ('born_alive', models.PositiveSmallIntegerField()),
                ('stillborn', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='births_as_dam', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_records', to='farms.farm')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_birth_records', to=settings.AUTH_USER_MODEL)),
                ('breeding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='birth_record', to='reproduction.breedingrecord')),
            ],
            options={
                'ordering': ['-birth_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='breedingrecord',
            index=models.Index(fields=['farm', 'status', 'expected_birth_date'], name='reproductio_farm_id_aecccc_idx'),
        ),
        migrations.AddIndex(
            model_name='birthrecord',
            index=models.Index(fields=['farm', 'birth_date'], name='reproductio_farm_id_7e6e18_idx'),
        ),
    ]
