# Generated by Django 5.2.16 on 2026-07-22 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('forage', 'Forage'), ('concentrate', 'Concentrate'), ('mineral', 'Mineral'), ('supplement', 'Supplement'), ('other', 'Other')], max_length=20)),
                ('suitability', models.CharField(choices=[('sheep', 'Sheep'), ('goat', 'Goat'), ('both', 'Sheep and goats')], default='both', max_length=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('life_stage', models.CharField(choices=[('maintenance', 'Maintenance'), ('growing', 'Growing'), ('gestation', 'Gestation'), ('lactation', 'Lactation'), ('finishing', 'Finishing'), ('custom', 'Custom')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='farms.farm')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='animals.flock')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedingPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_per_animal', models.DecimalField(decimal_places=3, max_digits=8)),
                ('feeding_time', models.CharField(blank=True, max_length=100)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='nutrition.feed')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.feedingplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feed',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_farm_feed'),
        ),
        migrations.AddConstraint(
            model_name='feedingplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'feed'), name='unique_plan_feed'),
        ),
    ]
