<script setup lang="ts">
import { AlertTriangle, Plus, Trash2 } from '@lucide/vue'
import type { Feed, FeedingPlan, Flock, Paginated } from '~/types/api'

const { request, selectedFarmId } = useApi()
const feeds = ref<Feed[]>([]); const flocks = ref<Flock[]>([]); const submitting = ref(false); const errorMessage = ref('')
const form = reactive({ flock: '', name: '', life_stage: 'maintenance', start_date: new Date().toISOString().slice(0, 10), end_date: '', notes: '', items: [{ feed: '', quantity_per_animal: '', feeding_time: '' }] })
function addItem() { form.items.push({ feed: '', quantity_per_animal: '', feeding_time: '' }) }
function removeItem(index: number) { if (form.items.length > 1) form.items.splice(index, 1) }
onMounted(async () => { if (!selectedFarmId.value) return; const [feedResponse, flockResponse] = await Promise.all([request<Paginated<Feed>>('/nutrition/feeds/'), request<Paginated<Flock>>('/animals/flocks/')]); feeds.value = feedResponse.results; flocks.value = flockResponse.results })
async function submit() { submitting.value = true; errorMessage.value = ''; try { await request<FeedingPlan>('/nutrition/plans/', { method: 'POST', body: { ...form, end_date: form.end_date || null } }); await navigateTo('/nutrition') } catch { errorMessage.value = 'The feeding plan could not be saved. Check the flock and feed entries.' } finally { submitting.value = false } }
</script>

<template><section class="form-card wide"><p class="eyebrow">Flock nutrition</p><h1>Create feeding plan</h1><div class="mt-5 flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><AlertTriangle class="mt-0.5 size-4 shrink-0" /><p>Use quantities agreed with a veterinarian or qualified nutritionist. Requirements vary with forage, body condition, climate, species, and production stage.</p></div><form class="form-grid" @submit.prevent="submit"><label>Plan name <input v-model="form.name" required maxlength="200"></label><label>Flock <select v-model="form.flock" required><option value="" disabled>Select flock</option><option v-for="flock in flocks" :key="flock.id" :value="flock.id">{{ flock.name }}</option></select></label><label>Life stage <select v-model="form.life_stage"><option value="maintenance">Maintenance</option><option value="growing">Growing</option><option value="gestation">Gestation</option><option value="lactation">Lactation</option><option value="finishing">Finishing</option><option value="custom">Custom</option></select></label><label>Start date <input v-model="form.start_date" type="date" required></label><label>End date <input v-model="form.end_date" type="date"></label><div class="full grid gap-3"><div class="flex items-center justify-between"><strong>Daily feed per animal</strong><Button type="button" size="sm" variant="outline" @click="addItem"><Plus /> Add feed</Button></div><div v-for="(item, index) in form.items" :key="index" class="grid gap-3 rounded-xl border p-4 sm:grid-cols-[1fr_1fr_1fr_auto]"><label>Feed <select v-model="item.feed" required><option value="" disabled>Select feed</option><option v-for="feed in feeds" :key="feed.id" :value="feed.id">{{ feed.name }} ({{ feed.unit }})</option></select></label><label>Quantity <input v-model="item.quantity_per_animal" type="number" min="0.001" step="0.001" required></label><label>Feeding time <input v-model="item.feeding_time" placeholder="e.g. Morning"></label><Button type="button" variant="ghost" size="icon" class="self-end" :disabled="form.items.length === 1" aria-label="Remove feed" @click="removeItem(index)"><Trash2 /></Button></div></div><label class="full">Notes <textarea v-model="form.notes" rows="3" /></label><p v-if="errorMessage" class="error full" role="alert">{{ errorMessage }}</p><div class="actions full"><Button as-child variant="ghost"><NuxtLink to="/nutrition">Cancel</NuxtLink></Button><Button type="submit" :disabled="submitting || !feeds.length || !flocks.length">{{ submitting ? 'Saving…' : 'Save plan' }}</Button></div></form></section></template>
