# Generated by Django 5.2.16 on 2026-07-22 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farminvitation_farmmembershipaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('flocks', 'Flocks'), ('animals', 'Animals'), ('weights', 'Weights'), ('medicine_batches', 'Medicine batches')], max_length=30)),
                ('mode', models.CharField(choices=[('all_or_nothing', 'All or nothing'), ('partial', 'Import valid rows')], max_length=20)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('completed', 'Completed'), ('failed', 'Failed')], default='previewed', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('rows', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_succeeded', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'status', 'created_at'], name='imports_imp_farm_id_bb3df3_idx')],
            },
        ),
    ]
